apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: rzv2nbs5a-go 
  janus-idp.io/tekton: rzv2nbs5a-go
  backstage.io/kubernetes-id: rzv2nbs5a-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: rzv2nbs5a-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml